# Blinded pharmacogenomics study — `corpus_only/rep3`

Maps 110 blinded cases (gene + drug + genotype description) to **diplotype → CPIC
metaboliser/function phenotype → guideline recommendation**.

Inputs: `cases_blinded.json`, `cpic_guideline_corpus.json` (CPIC snapshot 2026-05-09).
No network access was used. All mapping logic lives in `pgx_pipeline.py`, which this
notebook imports and drives, so the notebook and the script cannot drift apart.

In [1]:
import json, re, os, sys, collections
import pandas as pd

HERE = os.getcwd()
cases  = json.load(open(os.path.join(HERE, "cases_blinded.json")))
corpus = json.load(open(os.path.join(HERE, "cpic_guideline_corpus.json")))
print("cases:", len(cases))
print("corpus schema:", corpus["schema_version"], "| generated:", corpus["generated_at_utc"])
print("genes:", len(corpus["genes"]))

cases: 110
corpus schema: v3.1 | generated: 2026-05-10T04:40:15Z
genes: 21

## 1. Corpus inventory

What the supplied corpus does and does not contain. This determines which mapping steps
can be grounded in the corpus and which must come from the analyst's own knowledge.

In [2]:
inv = pd.DataFrame([
    {"gene": g, "chars": v["char_count"], "drugs_covered": ", ".join(v["drugs_covered"]),
     "n_source_annotations": len(v["sources"])}
    for g, v in corpus["genes"].items()])
display(inv.sort_values("gene").reset_index(drop=True))

ALL_TEXT = "\n".join(v["guideline_excerpt"] for v in corpus["genes"].values())
case_rsids = sorted(set(re.findall(r"rs\d+", json.dumps(cases))))
present = [r for r in case_rsids if r in ALL_TEXT]
print("rsIDs used by the cases :", len(case_rsids))
print("of those, found in corpus:", present)
print("allele-definition tables in corpus:", "CYP2C9 only (*1/*2/*3 via rs1799853/rs1057910)")

rsIDs used by the cases : 24
of those, found in corpus: ['rs1057910', 'rs113993960', 'rs12979860', 'rs4149056', 'rs75527207', 'rs9923231']
allele-definition tables in corpus: CYP2C9 only (*1/*2/*3 via rs1799853/rs1057910)

           gene  chars                                               drugs_covered  n_source_annotations
0          CFTR   2799                                                   ivacaftor                     1
1        CYP2B6   2252                                                   efavirenz                     1
2       CYP2C19  25574           citalopram, clopidogrel, omeprazole, voriconazole                     5
3        CYP2C9  11593                              celecoxib, phenytoin, warfarin                     3
4        CYP2D6  24781  amitriptyline, codeine, ondansetron, paroxetine, tamoxifen                     5
5        CYP3A5   1896                                                  tacrolimus                     1
6        CYP4F2    935                                                    warfarin                     1
7          DPYD   6061                                  capecitabine, fluorouracil                     2
8          G6PD   8699                                     primaquine, rasburicase                     2
9   HLA-A*31:01   3847                                               carbamazepine                     1
10  HLA-B*15:02   5803                                carbamazepine, oxcarbazepine                     2
11  HLA-B*57:01   1002                                                    abacavir                     1
12  HLA-B*58:01    976                                                 allopurinol                     1
13        IFNL3   1758                                                   PEG-IFN-α                     1
14      MT-RNR1   3284                                             aminoglycosides                     1
15       NUDT15   6508                                                 thiopurines                     1
16         RYR1   3798                                       volatile-anaesthetics                     1
17      SLCO1B1   6754                                   atorvastatin, simvastatin                     2
18         TPMT   6508                                                azathioprine                     1
19       UGT1A1   8661                                      atazanavir, irinotecan                     3
20       VKORC1    935                                                    warfarin                     1

## 2. Run the mapping pipeline

`pgx_pipeline.py` holds three explicit rule tables (assay→allele, diplotype→phenotype,
phenotype→recommendation) and asserts that **every recommendation string is a verbatim
substring of the supplied corpus**. Import executes it and writes all output files.

In [3]:
sys.path.insert(0, HERE)
import pgx_pipeline as P

cases=110  abstained=2  lethal_class=22
corpus sha256 (cases): bcda9e79e870a15e
corpus generated_at_utc: 2026-05-10T04:40:15Z | schema: v3.1

## 3. Table 1 — assay result → allele call

In [4]:
t1 = pd.read_csv("table_variant_to_allele.csv")
print(t1.basis.value_counts().to_dict())
display(t1[["gene","assay_result_pattern","allele_call","basis"]])

{'analyst-knowledge': 37, 'corpus': 14, 'case-annotation': 10}

           gene                   assay_result_pattern                                                                         allele_call              basis
0        CYP2D6                          rs3892097 T/T                                                                               *4/*4  analyst-knowledge
1        CYP2D6          rs3892097 C/T + rs1065852 G/A                                                                               *1/*4  analyst-knowledge
2        CYP2D6                          rs3892097 C/T                                                                               *1/*4  analyst-knowledge
3        CYP2D6   All CYP2D6 SNPs homozygous reference                                                                               *1/*1  analyst-knowledge
4        CYP2D6                       *1xN duplication                                                                             *1/*1xN    case-annotation
5       CYP2C19                          rs4244285 A/A                                                                               *2/*2  analyst-knowledge
6       CYP2C19                          rs4244285 G/A                                                                               *1/*2  analyst-knowledge
7       CYP2C19                         rs12248560 T/T                                                                             *17/*17  analyst-knowledge
8       CYP2C19                         rs12248560 C/T                                                                              *1/*17  analyst-knowledge
9       CYP2C19  All CYP2C19 SNPs homozygous reference                                                                               *1/*1  analyst-knowledge
10       CYP2C9                          rs1057910 C/C                                                                               *3/*3             corpus
11       CYP2C9                          rs1057910 A/C                                                                               *1/*3             corpus
12       CYP2C9   All CYP2C9 SNPs homozygous reference                                                                               *1/*1             corpus
13       CYP3A5                           rs776746 A/A                                                                               *1/*1    case-annotation
14       CYP3A5                           rs776746 A/G                                                                               *1/*3    case-annotation
15       CYP3A5                           rs776746 G/G                                                                               *3/*3    case-annotation
16       CYP2B6                          rs3745274 T/T                                                                               *6/*6  analyst-knowledge
17       CYP2B6                          rs3745274 G/T                                                                               *1/*6  analyst-knowledge
18       CYP2B6                          rs2279343 A/G                                                                               *1/*4  analyst-knowledge
19       CYP2B6   All CYP2B6 SNPs homozygous reference                                                                               *1/*1  analyst-knowledge
20         DPYD                          rs3918290 T/T                                                   c.1905+1G>A/c.1905+1G>A (*2A/*2A)  analyst-knowledge
21         DPYD                          rs3918290 C/T                                                      c.1905+1G>A/Reference (*1/*2A)  analyst-knowledge
22         DPYD                         rs56038477 C/T                                                          c.1236G>A(HapB3)/Reference  analyst-knowledge
23         DPYD       All DPYD risk variants reference                                                         Reference/Reference (*1/*1)  analyst-knowledge
24         TPMT          rs1800460 T/T + rs1142345 C/C                                                                             *3A/*3A  analyst-knowledge
25         TPMT                          rs1800460 C/T                                                                              *1/*3B  analyst-knowledge
26         TPMT                          rs1142345 T/C                                                                              *1/*3C  analyst-knowledge
27         TPMT     All TPMT SNPs homozygous reference                                                                               *1/*1  analyst-knowledge
28       NUDT15                        rs116855232 T/T                                                                               *3/*3  analyst-knowledge
29       NUDT15                        rs116855232 C/T                                                                               *1/*3  analyst-knowledge
..          ...                                    ...                                                                                 ...                ...
31      SLCO1B1                          rs4149056 C/C                                            *5/*5 (521CC; *15/*15 indistinguishable)             corpus
32      SLCO1B1                          rs4149056 T/C                                             *1/*5 (521TC; *1/*15 indistinguishable)             corpus
33      SLCO1B1                          rs4149056 T/T                                                                       *1/*1 (521TT)             corpus
34       UGT1A1                      rs8175347 TA7/TA7                                                                             *28/*28  analyst-knowledge
35       UGT1A1                      rs8175347 TA6/TA7                                                                              *1/*28  analyst-knowledge
36       UGT1A1                      rs8175347 TA6/TA6                                                                               *1/*1  analyst-knowledge
37  HLA-B*57:01                   rs2395029 G/T or G/G                               HLA-B*57:01 positive (inferred from HCP5 rs2395029 G)  analyst-knowledge
38  HLA-B*57:01                          rs2395029 T/T                             HLA-B*57:01 negative (inferred from HCP5 rs2395029 T/T)  analyst-knowledge
39  HLA-B*15:02                    positive for *15:02                                    HLA-B*15:02 positive (one or two *15:02 alleles)    case-annotation
40  HLA-B*15:02                    negative for *15:02                                                                HLA-B*15:02 negative    case-annotation
41  HLA-A*31:01                    positive for *31:01                                    HLA-A*31:01 positive (one or two *31:01 alleles)    case-annotation
42  HLA-A*31:01                    negative for *31:01                                                                HLA-A*31:01 negative    case-annotation
43  HLA-B*58:01                    positive for *58:01                                    HLA-B*58:01 positive (one or two *58:01 alleles)    case-annotation
44  HLA-B*58:01                    negative for *58:01                                                                HLA-B*58:01 negative    case-annotation
45         G6PD          rs5030868 A (hemizygous male)  Mediterranean (hemizygous male) or Mediterranean/Mediterranean (homozygous female)  analyst-knowledge
46         G6PD       rs1050828 T + rs1050829 C in cis                                   A- (hemizygous male) or A-/A- (homozygous female)  analyst-knowledge
47         G6PD              rs1050828 C/T + rs1050829                                                          B/A- (heterozygous female)  analyst-knowledge
48         G6PD              rs1050828 C + rs5030868 G                                      B (hemizygous male) or B/B (homozygous female)  analyst-knowledge
49        IFNL3                         rs12979860 C/C                                                                      rs12979860 C/C             corpus
50        IFNL3                         rs12979860 T/T                                                                      rs12979860 T/T             corpus
51       VKORC1                          rs9923231 A/A                                                            rs9923231 (-1639G>A) A/A             corpus
52       VKORC1                          rs9923231 G/G                                                            rs9923231 (-1639G>A) G/G             corpus
53       CYP4F2                          rs2108622 T/T                                                                               *3/*3  analyst-knowledge
54       CYP4F2                          rs2108622 C/C                                                                               *1/*1  analyst-knowledge
55         CFTR                  rs75527207 G/A or A/A                                                G551D positive (rs75527207 AA or AG)             corpus
56         CFTR       rs113993960 (F508del homozygous)                                                                     F508del/F508del             corpus
57      MT-RNR1                              m.1555A>G                                                             m.1555A>G (homoplasmic)  analyst-knowledge
58      MT-RNR1                   m.1555A (no variant)                                                                 m.1555A (reference)  analyst-knowledge
59         RYR1                          RYR1 mutation                                          RYR1 c.1840C>T p.(Arg614Cys), heterozygous             corpus
60         RYR1             RYR1 no pathogenic variant                                       No RYR1/CACNA1S MH-causative variant detected             corpus

## 4. Table 2 — diplotype → phenotype

In [5]:
t2 = pd.read_csv("table_diplotype_to_phenotype.csv")
display(t2)

           gene                                                                           diplotype activity_score                                                                            phenotype
0        CYP2D6                                                                               *4/*4              0                                                              CYP2D6 poor metabolizer
1        CYP2D6                                                                               *1/*4            1.0                                                      CYP2D6 intermediate metabolizer
2        CYP2D6                                                                               *1/*1            2.0                                                            CYP2D6 normal metabolizer
3        CYP2D6                                                                             *1/*1xN          >2.25                                                        CYP2D6 ultrarapid metabolizer
4       CYP2C19                                                                               *2/*2            NaN                                                             CYP2C19 poor metabolizer
5       CYP2C19                                                                               *1/*2            NaN                                                     CYP2C19 intermediate metabolizer
6       CYP2C19                                                                               *1/*1            NaN                                                           CYP2C19 normal metabolizer
7       CYP2C19                                                                              *1/*17            NaN                                                            CYP2C19 rapid metabolizer
8       CYP2C19                                                                             *17/*17            NaN                                                       CYP2C19 ultrarapid metabolizer
9        CYP2C9                                                                               *3/*3              0                                                              CYP2C9 poor metabolizer
10       CYP2C9                                                                               *1/*3              1                                                      CYP2C9 intermediate metabolizer
11       CYP2C9                                                                               *1/*1              2                                                            CYP2C9 normal metabolizer
12       CYP3A5                                                                               *1/*1            NaN                  CYP3A5 normal metabolizer (extensive metabolizer, CYP3A5 expresser)
13       CYP3A5                                                                               *1/*3            NaN                                   CYP3A5 intermediate metabolizer (CYP3A5 expresser)
14       CYP3A5                                                                               *3/*3            NaN                                       CYP3A5 poor metabolizer (CYP3A5 non-expresser)
15       CYP2B6                                                                               *6/*6            NaN                                                              CYP2B6 poor metabolizer
16       CYP2B6                                                                               *1/*6            NaN                                                      CYP2B6 intermediate metabolizer
17       CYP2B6                                                                               *1/*1            NaN                                                            CYP2B6 normal metabolizer
18       CYP2B6                                                                               *1/*4            NaN                                                             CYP2B6 rapid metabolizer
19         DPYD                                                   c.1905+1G>A/c.1905+1G>A (*2A/*2A)              0                                                                DPYD poor metabolizer
20         DPYD                                                      c.1905+1G>A/Reference (*1/*2A)              1                                                        DPYD intermediate metabolizer
21         DPYD                                                          c.1236G>A(HapB3)/Reference            1.5                                                        DPYD intermediate metabolizer
22         DPYD                                                         Reference/Reference (*1/*1)              2                                                              DPYD normal metabolizer
23         TPMT                                                                             *3A/*3A            NaN                                                                TPMT poor metabolizer
24         TPMT                                                                              *1/*3B            NaN                                                        TPMT intermediate metabolizer
25         TPMT                                                                              *1/*3C            NaN                                                        TPMT intermediate metabolizer
26         TPMT                                                                               *1/*1            NaN                                                              TPMT normal metabolizer
27       NUDT15                                                                               *3/*3            NaN                                                              NUDT15 poor metabolizer
28       NUDT15                                                                               *1/*3            NaN                                                      NUDT15 intermediate metabolizer
29       NUDT15                                                                               *1/*1            NaN                                                            NUDT15 normal metabolizer
30      SLCO1B1                                            *5/*5 (521CC; *15/*15 indistinguishable)            NaN                                                                SLCO1B1 poor function
31      SLCO1B1                                             *1/*5 (521TC; *1/*15 indistinguishable)            NaN                                                           SLCO1B1 decreased function
32      SLCO1B1                                                                       *1/*1 (521TT)            NaN                                                              SLCO1B1 normal function
33       UGT1A1                                                                             *28/*28            NaN                                                              UGT1A1 poor metabolizer
34       UGT1A1                                                                              *1/*28            NaN                                                      UGT1A1 intermediate metabolizer
35       UGT1A1                                                                               *1/*1            NaN                                                UGT1A1 extensive (normal) metabolizer
36  HLA-B*57:01                               HLA-B*57:01 positive (inferred from HCP5 rs2395029 G)            NaN                        High risk of abacavir hypersensitivity (HLA-B*57:01 positive)
37  HLA-B*57:01                             HLA-B*57:01 negative (inferred from HCP5 rs2395029 T/T)            NaN                    Very low risk of abacavir hypersensitivity (HLA-B*57:01 negative)
38  HLA-B*15:02                                    HLA-B*15:02 positive (one or two *15:02 alleles)            NaN  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)
39  HLA-B*15:02                                                                HLA-B*15:02 negative            NaN                            Normal risk of HLA-B*15:02-mediated SJS/TEN (non-carrier)
40  HLA-A*31:01                                    HLA-A*31:01 positive (one or two *31:01 alleles)            NaN       Increased risk of carbamazepine-induced hypersensitivity (HLA-A*31:01 carrier)
41  HLA-A*31:01                                                                HLA-A*31:01 negative            NaN                   Normal risk of HLA-A*31:01-mediated hypersensitivity (non-carrier)
42  HLA-B*58:01                                    HLA-B*58:01 positive (one or two *58:01 alleles)            NaN               Significantly increased risk of allopurinol SCAR (HLA-B*58:01 carrier)
43  HLA-B*58:01                                                                HLA-B*58:01 negative            NaN                                Low or reduced risk of allopurinol SCAR (non-carrier)
44         G6PD  Mediterranean (hemizygous male) or Mediterranean/Mediterranean (homozygous female)            NaN                                                        G6PD Deficient (WHO class II)
45         G6PD                                   A- (hemizygous male) or A-/A- (homozygous female)            NaN                                                       G6PD Deficient (WHO class III)
46         G6PD                                                          B/A- (heterozygous female)            NaN                                                                        G6PD Variable
47         G6PD                                      B (hemizygous male) or B/B (homozygous female)            NaN                                                           G6PD Normal (WHO class IV)
48        IFNL3                                                                      rs12979860 C/C            NaN                                                          Favorable response genotype
49        IFNL3                                                                      rs12979860 T/T            NaN                                                        Unfavorable response genotype
50       VKORC1                                                            rs9923231 (-1639G>A) A/A            NaN        VKORC1 -1639 A/A: increased warfarin sensitivity (decreased dose requirement)
51       VKORC1                                                            rs9923231 (-1639G>A) G/G            NaN                                        VKORC1 -1639 G/G: normal warfarin sensitivity
52       CYP4F2                                                                               *3/*3            NaN                                            CYP4F2 decreased function (*3 homozygote)
53       CYP4F2                                                                               *1/*1            NaN                                                               CYP4F2 normal function
54         CFTR                                                G551D positive (rs75527207 AA or AG)            NaN                            CFTR ivacaftor-responsive genotype (G551D gating variant)
55         CFTR                                                                     F508del/F508del            NaN                          CFTR ivacaftor-non-responsive genotype (F508del homozygote)
56      MT-RNR1                                                             m.1555A>G (homoplasmic)            NaN                        MT-RNR1 increased risk of aminoglycoside-induced hearing loss
57      MT-RNR1                                                                 m.1555A (reference)            NaN                           MT-RNR1 normal risk of aminoglycoside-induced hearing loss
58         RYR1                                          RYR1 c.1840C>T p.(Arg614Cys), heterozygous            NaN                                                   Malignant Hyperthermia susceptible
59         RYR1                                       No RYR1/CACNA1S MH-causative variant detected            NaN                                                             Uncertain susceptibility

## 5. Table 3 — (gene, drug, phenotype) → recommendation

In [6]:
t3 = pd.read_csv("table_phenotype_to_recommendation.csv")
print("gene-drug-phenotype rules:", len(t3))
display(t3[["gene","drug","phenotype","action","guideline_source","abstained"]])

gene-drug-phenotype rules: 109

            gene                   drug                                                                            phenotype                                                                                                                                                                                                                      action  guideline_source  abstained
0         CYP2D6                codeine                                                        CYP2D6 ultrarapid metabolizer                                                                                                                     codeine: avoid - risk of serious morphine toxicity; if an opioid is warranted use a non-tramadol opioid  CPIC PA166104996      False
1         CYP2D6                codeine                                                            CYP2D6 normal metabolizer                                                                                                                                                               codeine: use label-recommended age- or weight-specific dosing  CPIC PA166104996      False
2         CYP2D6                codeine                                                      CYP2D6 intermediate metabolizer                                                                                    codeine: use label-recommended age- or weight-specific dosing; if no response and an opioid is warranted, consider a non-tramadol opioid  CPIC PA166104996      False
3         CYP2D6                codeine                                                              CYP2D6 poor metabolizer                                                                                                                                  codeine: avoid - diminished analgesia; if an opioid is warranted use a non-tramadol opioid  CPIC PA166104996      False
4         CYP2D6              tamoxifen                                                        CYP2D6 ultrarapid metabolizer                                                                                                                                               tamoxifen: standard dosing 20 mg/day; avoid moderate/strong CYP2D6 inhibitors  CPIC PA166176068      False
5         CYP2D6              tamoxifen                                                            CYP2D6 normal metabolizer                                                                                                                                               tamoxifen: standard dosing 20 mg/day; avoid moderate/strong CYP2D6 inhibitors  CPIC PA166176068      False
6         CYP2D6              tamoxifen                                                      CYP2D6 intermediate metabolizer                                        tamoxifen: consider an aromatase inhibitor instead (plus ovarian suppression if premenopausal); if an AI is contraindicated consider tamoxifen 40 mg/day and avoid CYP2D6 inhibitors  CPIC PA166176068      False
7         CYP2D6              tamoxifen                                                              CYP2D6 poor metabolizer                                                                                                        tamoxifen: avoid - use alternative hormonal therapy (aromatase inhibitor, plus ovarian suppression if premenopausal)  CPIC PA166176068      False
8         CYP2D6            ondansetron                                                        CYP2D6 ultrarapid metabolizer                                                                                                            ondansetron: avoid - select an alternative antiemetic not predominantly metabolised by CYP2D6 (e.g. granisetron)  CPIC PA166161954      False
9         CYP2D6            ondansetron                                                            CYP2D6 normal metabolizer                                                                                                                                                            ondansetron: initiate therapy with the recommended starting dose  CPIC PA166161954      False
10        CYP2D6            ondansetron                                                      CYP2D6 intermediate metabolizer                                                                                                        ondansetron: initiate therapy with the recommended starting dose (insufficient evidence for a genotype-based change)  CPIC PA166161954      False
11        CYP2D6            ondansetron                                                              CYP2D6 poor metabolizer                                                                                                        ondansetron: initiate therapy with the recommended starting dose (insufficient evidence for a genotype-based change)  CPIC PA166161954      False
12        CYP2D6             paroxetine                                                        CYP2D6 ultrarapid metabolizer                                                                                                                            paroxetine: avoid - select an alternative antidepressant not predominantly metabolised by CYP2D6  CPIC PA166127636      False
13        CYP2D6             paroxetine                                                            CYP2D6 normal metabolizer                                                                                                                                                             paroxetine: initiate therapy with the recommended starting dose  CPIC PA166127636      False
14        CYP2D6             paroxetine                                                      CYP2D6 intermediate metabolizer                                                                                                                                paroxetine: consider a lower starting dose and slower titration than for normal metabolisers  CPIC PA166127636      False
15        CYP2D6             paroxetine                                                              CYP2D6 poor metabolizer                                                                                                                             paroxetine: consider a 50% lower starting dose, slower titration and 50% lower maintenance dose  CPIC PA166127636      False
16        CYP2D6          amitriptyline                                                        CYP2D6 ultrarapid metabolizer                                                                                                          amitriptyline: avoid (assuming CYP2C19 normal metaboliser); if warranted, titrate to a higher target dose with TDM  CPIC PA166105006      False
17        CYP2D6          amitriptyline                                                            CYP2D6 normal metabolizer                                                                                                                    amitriptyline: initiate therapy with the recommended starting dose (assuming CYP2C19 normal metaboliser)  CPIC PA166105006      False
18        CYP2D6          amitriptyline                                                      CYP2D6 intermediate metabolizer                                                                                                     amitriptyline: consider a 25% reduction of the recommended starting dose with TDM (assuming CYP2C19 normal metaboliser)  CPIC PA166105006      False
19        CYP2D6          amitriptyline                                                              CYP2D6 poor metabolizer                                                                                           amitriptyline: avoid (assuming CYP2C19 normal metaboliser); if warranted, 50% reduction of the recommended starting dose with TDM  CPIC PA166105006      False
20       CYP2C19            clopidogrel                                                       CYP2C19 ultrarapid metabolizer                                                                                                                                                                               clopidogrel: use at standard dose (75 mg/day)  CPIC PA166104948      False
21       CYP2C19            clopidogrel                                                            CYP2C19 rapid metabolizer                                                                                                                                                                               clopidogrel: use at standard dose (75 mg/day)  CPIC PA166104948      False
22       CYP2C19            clopidogrel                                                           CYP2C19 normal metabolizer                                                                                                                                                                               clopidogrel: use at standard dose (75 mg/day)  CPIC PA166104948      False
23       CYP2C19            clopidogrel                                                     CYP2C19 intermediate metabolizer                                                                                                          clopidogrel: avoid standard dose if possible - use prasugrel or ticagrelor at standard dose if not contraindicated  CPIC PA166104948      False
24       CYP2C19            clopidogrel                                                             CYP2C19 poor metabolizer                                                                                                                        clopidogrel: avoid if possible - use prasugrel or ticagrelor at standard dose if not contraindicated  CPIC PA166104948      False
25       CYP2C19           voriconazole                                                       CYP2C19 ultrarapid metabolizer                                                                                                      voriconazole: avoid - choose an agent not dependent on CYP2C19 (isavuconazole, liposomal amphotericin B, posaconazole)  CPIC PA166161537      False
26       CYP2C19           voriconazole                                                            CYP2C19 rapid metabolizer                                                                                            voriconazole: avoid in adults - choose an agent not dependent on CYP2C19 (isavuconazole, liposomal amphotericin B, posaconazole)  CPIC PA166161537      False
27       CYP2C19           voriconazole                                                           CYP2C19 normal metabolizer                                                                                                                                                     voriconazole: initiate therapy with recommended standard-of-care dosing  CPIC PA166161537      False
28       CYP2C19           voriconazole                                                     CYP2C19 intermediate metabolizer                                                                                                                                                     voriconazole: initiate therapy with recommended standard-of-care dosing  CPIC PA166161537      False
29       CYP2C19           voriconazole                                                             CYP2C19 poor metabolizer                                                                                           voriconazole: avoid - choose an agent not dependent on CYP2C19; if voriconazole is unavoidable, use a lower dose with careful TDM  CPIC PA166161537      False
..           ...                    ...                                                                                  ...                                                                                                                                                                                                                         ...               ...        ...
79        UGT1A1             atazanavir                                                      UGT1A1 intermediate metabolizer                                                                                                              atazanavir: no need to avoid atazanavir; advise that bilirubin-related jaundice is unlikely with this genotype  CPIC PA166128738      False
80        UGT1A1             atazanavir                                                              UGT1A1 poor metabolizer                                                                                                                            atazanavir: consider an alternative agent, particularly where jaundice would concern the patient  CPIC PA166128738      False
81        UGT1A1             irinotecan                                                UGT1A1 extensive (normal) metabolizer                                                                                                                irinotecan: no action needed for this gene-drug interaction (DPWG; no CPIC guideline in the supplied corpus)  DPWG PA166104951      False
82        UGT1A1             irinotecan                                                      UGT1A1 intermediate metabolizer                                                                                                                irinotecan: no action needed for this gene-drug interaction (DPWG; no CPIC guideline in the supplied corpus)  DPWG PA166104951      False
83        UGT1A1             irinotecan                                                              UGT1A1 poor metabolizer                                                                                  irinotecan: start at 70% of the normal dose and escalate on neutrophil count if tolerated (DPWG; no CPIC guideline in the supplied corpus)  DPWG PA166104951      False
84   HLA-B*57:01               abacavir                        High risk of abacavir hypersensitivity (HLA-B*57:01 positive)                                                                                                                                      abacavir: avoid - abacavir is not recommended (high risk of hypersensitivity reaction)  CPIC PA166104997      False
85   HLA-B*57:01               abacavir                    Very low risk of abacavir hypersensitivity (HLA-B*57:01 negative)                                                                                                                                                                                abacavir: use per standard dosing guidelines  CPIC PA166104997      False
86   HLA-B*58:01            allopurinol               Significantly increased risk of allopurinol SCAR (HLA-B*58:01 carrier)                                                                                                                             allopurinol: avoid - allopurinol is contraindicated (risk of severe cutaneous adverse reaction)  CPIC PA166105003      False
87   HLA-B*58:01            allopurinol                                Low or reduced risk of allopurinol SCAR (non-carrier)                                                                                                                                                                             allopurinol: use per standard dosing guidelines  CPIC PA166105003      False
88   HLA-B*15:02          carbamazepine  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)                                                                                                                    carbamazepine: avoid - if the patient is carbamazepine-naive, do not use carbamazepine (risk of SJS/TEN)  CPIC PA166105008      False
89   HLA-B*15:02          carbamazepine                            Normal risk of HLA-B*15:02-mediated SJS/TEN (non-carrier)                                                                                                                           carbamazepine: use per standard dosing guidelines (assumes HLA-A*31:01 also non-carrier/untested)  CPIC PA166105008      False
90   HLA-B*15:02          oxcarbazepine  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)                                                                                                                    oxcarbazepine: avoid - if the patient is oxcarbazepine-naive, do not use oxcarbazepine (risk of SJS/TEN)  CPIC PA166176623      False
91   HLA-B*15:02          oxcarbazepine                            Normal risk of HLA-B*15:02-mediated SJS/TEN (non-carrier)                                                                                                                                                                           oxcarbazepine: use per standard dosing guidelines  CPIC PA166176623      False
92   HLA-A*31:01          carbamazepine       Increased risk of carbamazepine-induced hypersensitivity (HLA-A*31:01 carrier)                             carbamazepine: avoid if the patient is carbamazepine-naive and alternatives exist; if no alternative, use with increased clinical monitoring and stop at the first sign of a cutaneous reaction  CPIC PA166105008      False
93   HLA-A*31:01          carbamazepine                   Normal risk of HLA-A*31:01-mediated hypersensitivity (non-carrier)                                                                                                                           carbamazepine: use per standard dosing guidelines (assumes HLA-B*15:02 also non-carrier/untested)  CPIC PA166105008      False
94          G6PD            rasburicase                                                        G6PD Deficient (WHO class II)                                                                                                                                                 rasburicase: contraindicated - do not use; alternatives include allopurinol  CPIC PA166267376      False
95          G6PD            rasburicase                                                       G6PD Deficient (WHO class III)                                                                                                                                                 rasburicase: contraindicated - do not use; alternatives include allopurinol  CPIC PA166267376      False
96          G6PD            rasburicase                                                           G6PD Normal (WHO class IV)                                                                                                                                                         rasburicase: no reason to withhold rasburicase based on G6PD status  CPIC PA166267376      False
97          G6PD            rasburicase                                                                        G6PD Variable                                                                                              rasburicase: do not give until G6PD enzyme activity has been measured and shown to be normal; alternatives include allopurinol  CPIC PA166267376      False
98          G6PD             primaquine                                                       G6PD Deficient (WHO class III)  primaquine: avoid standard 14-day dosing - high risk of acute haemolytic anaemia; if radical cure is needed use the WHO/CDC weekly regimen (0.75 mg/kg or 45 mg once weekly x8 weeks) with close monitoring for haemolysis  CPIC PA166279621      False
99          G6PD             primaquine                                                           G6PD Normal (WHO class IV)                                                                                                                                                              primaquine: no reason to avoid primaquine based on G6PD status  CPIC PA166279621      False

## 6. Answers

In [7]:
ans = pd.read_csv("claude_science_answers.csv")
aud = pd.read_csv("answers_audit_trail.csv")
assert list(ans.columns) == ["case_id","diplotype","phenotype","recommendation","abstained"]
assert len(ans) == 110 and ans.case_id.is_unique
assert set(ans.case_id) == {c["id"] for c in cases}
print("rows:", len(ans), "| abstained:", int(ans.abstained.sum()),
      "| lethal-class:", int(aud.lethal_class.sum()))
display(ans.head(12))

rows: 110 | abstained: 2 | lethal-class: 22

         case_id diplotype                        phenotype                                                                                                                                                                        recommendation  abstained
0   70dc9c9110f3     *4/*4          CYP2D6 poor metabolizer                                                                                            codeine: avoid - diminished analgesia; if an opioid is warranted use a non-tramadol opioid      False
1   b07cff8c99c0     *1/*4  CYP2D6 intermediate metabolizer                                              codeine: use label-recommended age- or weight-specific dosing; if no response and an opioid is warranted, consider a non-tramadol opioid      False
2   ce34b1a18a3d     *1/*1        CYP2D6 normal metabolizer                                                                                                                         codeine: use label-recommended age- or weight-specific dosing      False
3   74597c5503ec   *1/*1xN    CYP2D6 ultrarapid metabolizer                                                                               codeine: avoid - risk of serious morphine toxicity; if an opioid is warranted use a non-tramadol opioid      False
4   3d0e97b86ad0     *1/*4  CYP2D6 intermediate metabolizer                                              codeine: use label-recommended age- or weight-specific dosing; if no response and an opioid is warranted, consider a non-tramadol opioid      False
5   f9e4a13551fd     *4/*4          CYP2D6 poor metabolizer                                                                  tamoxifen: avoid - use alternative hormonal therapy (aromatase inhibitor, plus ovarian suppression if premenopausal)      False
6   9d75134030af     *1/*4  CYP2D6 intermediate metabolizer  tamoxifen: consider an aromatase inhibitor instead (plus ovarian suppression if premenopausal); if an AI is contraindicated consider tamoxifen 40 mg/day and avoid CYP2D6 inhibitors      False
7   987d7bd14933     *1/*1        CYP2D6 normal metabolizer                                                                                                         tamoxifen: standard dosing 20 mg/day; avoid moderate/strong CYP2D6 inhibitors      False
8   61741d10f238   *1/*1xN    CYP2D6 ultrarapid metabolizer                                                                                                         tamoxifen: standard dosing 20 mg/day; avoid moderate/strong CYP2D6 inhibitors      False
9   c0cb8d7ad685     *4/*4          CYP2D6 poor metabolizer                                                                  ondansetron: initiate therapy with the recommended starting dose (insufficient evidence for a genotype-based change)      False
10  3ac7c0b0f795     *1/*1        CYP2D6 normal metabolizer                                                                                                                      ondansetron: initiate therapy with the recommended starting dose      False
11  01166e2ea9ad   *1/*1xN    CYP2D6 ultrarapid metabolizer                                                                      ondansetron: avoid - select an alternative antiemetic not predominantly metabolised by CYP2D6 (e.g. granisetron)      False

### Phenotype coverage per gene

In [8]:
cov = (aud.groupby(["gene","phenotype"]).size().rename("n").reset_index()
         .sort_values(["gene","phenotype"]))
display(cov)

           gene                                                                            phenotype  n
0          CFTR                          CFTR ivacaftor-non-responsive genotype (F508del homozygote)  1
1          CFTR                            CFTR ivacaftor-responsive genotype (G551D gating variant)  1
2        CYP2B6                                                      CYP2B6 intermediate metabolizer  1
3        CYP2B6                                                            CYP2B6 normal metabolizer  1
4        CYP2B6                                                              CYP2B6 poor metabolizer  1
5        CYP2B6                                                             CYP2B6 rapid metabolizer  1
6       CYP2C19                                                     CYP2C19 intermediate metabolizer  4
7       CYP2C19                                                           CYP2C19 normal metabolizer  4
8       CYP2C19                                                             CYP2C19 poor metabolizer  4
9       CYP2C19                                                            CYP2C19 rapid metabolizer  4
10      CYP2C19                                                       CYP2C19 ultrarapid metabolizer  4
11       CYP2C9                                                      CYP2C9 intermediate metabolizer  3
12       CYP2C9                                                            CYP2C9 normal metabolizer  3
13       CYP2C9                                                              CYP2C9 poor metabolizer  3
14       CYP2D6                                                      CYP2D6 intermediate metabolizer  5
15       CYP2D6                                                            CYP2D6 normal metabolizer  5
16       CYP2D6                                                              CYP2D6 poor metabolizer  5
17       CYP2D6                                                        CYP2D6 ultrarapid metabolizer  5
18       CYP3A5                                   CYP3A5 intermediate metabolizer (CYP3A5 expresser)  1
19       CYP3A5                  CYP3A5 normal metabolizer (extensive metabolizer, CYP3A5 expresser)  1
20       CYP3A5                                       CYP3A5 poor metabolizer (CYP3A5 non-expresser)  1
21       CYP4F2                                            CYP4F2 decreased function (*3 homozygote)  1
22       CYP4F2                                                               CYP4F2 normal function  1
23         DPYD                                                        DPYD intermediate metabolizer  3
24         DPYD                                                              DPYD normal metabolizer  2
25         DPYD                                                                DPYD poor metabolizer  2
26         G6PD                                                        G6PD Deficient (WHO class II)  1
27         G6PD                                                       G6PD Deficient (WHO class III)  2
28         G6PD                                                           G6PD Normal (WHO class IV)  2
29         G6PD                                                                        G6PD Variable  1
30  HLA-A*31:01       Increased risk of carbamazepine-induced hypersensitivity (HLA-A*31:01 carrier)  1
31  HLA-A*31:01                   Normal risk of HLA-A*31:01-mediated hypersensitivity (non-carrier)  1
32  HLA-B*15:02  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)  2
33  HLA-B*15:02                            Normal risk of HLA-B*15:02-mediated SJS/TEN (non-carrier)  2
34  HLA-B*57:01                        High risk of abacavir hypersensitivity (HLA-B*57:01 positive)  1
35  HLA-B*57:01                    Very low risk of abacavir hypersensitivity (HLA-B*57:01 negative)  1
36  HLA-B*58:01                                Low or reduced risk of allopurinol SCAR (non-carrier)  1
37  HLA-B*58:01               Significantly increased risk of allopurinol SCAR (HLA-B*58:01 carrier)  1
38        IFNL3                                                          Favorable response genotype  1
39        IFNL3                                                        Unfavorable response genotype  1
40      MT-RNR1                        MT-RNR1 increased risk of aminoglycoside-induced hearing loss  1
41      MT-RNR1                           MT-RNR1 normal risk of aminoglycoside-induced hearing loss  1
42       NUDT15                                                      NUDT15 intermediate metabolizer  1
43       NUDT15                                                            NUDT15 normal metabolizer  1
44       NUDT15                                                              NUDT15 poor metabolizer  1
45         RYR1                                                   Malignant Hyperthermia susceptible  1
46         RYR1                                                             Uncertain susceptibility  1
47      SLCO1B1                                                           SLCO1B1 decreased function  2
48      SLCO1B1                                                              SLCO1B1 normal function  2
49      SLCO1B1                                                                SLCO1B1 poor function  2
50         TPMT                                                        TPMT intermediate metabolizer  2
51         TPMT                                                              TPMT normal metabolizer  1
52         TPMT                                                                TPMT poor metabolizer  1
53       UGT1A1                                                UGT1A1 extensive (normal) metabolizer  2
54       UGT1A1                                                      UGT1A1 intermediate metabolizer  2
55       UGT1A1                                                              UGT1A1 poor metabolizer  2
56       VKORC1        VKORC1 -1639 A/A: increased warfarin sensitivity (decreased dose requirement)  1
57       VKORC1                                        VKORC1 -1639 G/G: normal warfarin sensitivity  1

### Abstentions

In [9]:
pd.set_option("display.max_colwidth", 200)
display(aud[aud.abstained][["case_id","gene","drug","diplotype","phenotype","recommendation"]])

          case_id    gene      drug diplotype                                  phenotype                                                                                                                                                                                          recommendation
102  e55c1b0dd1a0  CYP4F2  warfarin     *3/*3  CYP4F2 decreased function (*3 homozygote)  warfarin: ABSTAIN - the supplied CPIC excerpt gives no CYP4F2 genotype-specific dose recommendation (its only dose table is VKORC1 x CYP2C9); a CYP4F2-only result cannot be translated into an action
103  807ece818520  CYP4F2  warfarin     *1/*1                     CYP4F2 normal function  warfarin: ABSTAIN - the supplied CPIC excerpt gives no CYP4F2 genotype-specific dose recommendation (its only dose table is VKORC1 x CYP2C9); a CYP4F2-only result cannot be translated into an action

### Lethal-class cases

Cases where standard dosing of the named drug in the called phenotype can plausibly kill
or cause irreversible major organ/tissue injury — not merely treatment failure.

In [10]:
display(aud[aud.lethal_class][["case_id","gene","drug","phenotype","recommendation","lethal_rationale"]]
        .reset_index(drop=True))

         case_id         gene                   drug                                                                            phenotype                                                                                                                                                                                                                      recommendation                                                                                                   lethal_rationale
0   74597c5503ec       CYP2D6                codeine                                                        CYP2D6 ultrarapid metabolizer                                                                                                                             codeine: avoid - risk of serious morphine toxicity; if an opioid is warranted use a non-tramadol opioid                   Ultrarapid morphine formation; documented fatal/near-fatal respiratory depression at label doses
1   ca9e14feca53      CYP2C19            clopidogrel                                                             CYP2C19 poor metabolizer                                                                                                                                clopidogrel: avoid if possible - use prasugrel or ticagrelor at standard dose if not contraindicated                                         Loss of antiplatelet effect; stent thrombosis, MI and cardiovascular death
2   97c3baebed4e       CYP2C9               warfarin                                                              CYP2C9 poor metabolizer  warfarin: use a validated genotype-guided dosing algorithm; corpus dose table gives an expected stable dose of only 0.5-2 mg/day (CYP2C9 *3/*3, assuming VKORC1 -1639 GG) - standard initiation carries a high major-bleeding risk                                       Stable dose 0.5-2 mg/day; standard initiation causes major/fatal haemorrhage
3   b94a43e574db         DPYD           fluorouracil                                                                DPYD poor metabolizer                                                                                                                  fluorouracil: avoid - do not use 5-fluorouracil or 5-fluorouracil prodrug-based regimens (complete DPD deficiency)                                        Complete DPD deficiency; corpus states 'severe or even fatal drug toxicity'
4   c57caa44a38a         DPYD           fluorouracil                                                        DPYD intermediate metabolizer                                                                                                                                                         fluorouracil: reduce the starting dose by 50%, then titrate on toxicity/TDM                            Partial DPD deficiency; corpus states 'severe or even fatal drug toxicity' at full dose
5   6b8d2db91001         DPYD           fluorouracil                                                        DPYD intermediate metabolizer                                                                                                                                                         fluorouracil: reduce the starting dose by 50%, then titrate on toxicity/TDM                            Partial DPD deficiency; corpus states 'severe or even fatal drug toxicity' at full dose
6   c6549d637d49         DPYD           capecitabine                                                                DPYD poor metabolizer                                                                                                                  capecitabine: avoid - do not use 5-fluorouracil or 5-fluorouracil prodrug-based regimens (complete DPD deficiency)                                        Complete DPD deficiency; corpus states 'severe or even fatal drug toxicity'
7   ae4a7215ae64         DPYD           capecitabine                                                        DPYD intermediate metabolizer                                                                                                                                                         capecitabine: reduce the starting dose by 50%, then titrate on toxicity/TDM                            Partial DPD deficiency; corpus states 'severe or even fatal drug toxicity' at full dose
8   08e18e809fcb         TPMT           azathioprine                                                                TPMT poor metabolizer                                                        azathioprine: avoid standard dosing - consider an alternative immunosuppressant; if a thiopurine is used, drastic dose reduction is required (tolerated dose ~10% of normal)                                             Profound prolonged myelosuppression at conventional dose; can be fatal
9   f3dd19d8a337       NUDT15            thiopurines                                                              NUDT15 poor metabolizer                                                                          thiopurines (azathioprine/mercaptopurine/thioguanine): avoid standard dosing - consider an alternative immunosuppressant; tolerated dose is ~10% of normal                                        Severe myelosuppression at conventional dose; tolerated dose ~10% of normal
10  d1a12c4a16c4      SLCO1B1            simvastatin                                                                SLCO1B1 poor function                                                                                                                        simvastatin: avoid - prescribe an alternative statin of the desired potency (highly increased myopathy risk)                                                                    Rhabdomyolysis with renal failure; can be fatal
11  4f19dd3f5283       UGT1A1             irinotecan                                                              UGT1A1 poor metabolizer                                                                                          irinotecan: start at 70% of the normal dose and escalate on neutrophil count if tolerated (DPWG; no CPIC guideline in the supplied corpus)  Corpus states 'serious, life-threatening adverse events occur more often' (febrile neutropenia, severe diarrhoea)
12  e70379d3dbac  HLA-B*57:01               abacavir                        High risk of abacavir hypersensitivity (HLA-B*57:01 positive)                                                                                                                                              abacavir: avoid - abacavir is not recommended (high risk of hypersensitivity reaction)                                                                    Systemic hypersensitivity; fatal on rechallenge
13  7181a24a65d5  HLA-B*15:02          carbamazepine  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)                                                                                                                            carbamazepine: avoid - if the patient is carbamazepine-naive, do not use carbamazepine (risk of SJS/TEN)                                                                                 SJS/TEN with substantial mortality
14  569a842e1a9a  HLA-B*15:02          oxcarbazepine  Increased risk of carbamazepine/oxcarbazepine-induced SJS/TEN (HLA-B*15:02 carrier)                                                                                                                            oxcarbazepine: avoid - if the patient is oxcarbazepine-naive, do not use oxcarbazepine (risk of SJS/TEN)                                                                                 SJS/TEN with substantial mortality
15  85976e86289a  HLA-A*31:01          carbamazepine       Increased risk of carbamazepine-induced hypersensitivity (HLA-A*31:01 carrier)                                     carbamazepine: avoid if the patient is carbamazepine-naive and alternatives exist; if no alternative, use with increased clinical monitoring and stop at the first sign of a cutaneous reaction                                                                                        DRESS/SJS/TEN; can be fatal
16  ebf82c3bcfdd  HLA-B*58:01            allopurinol               Significantly increased risk of allopurinol SCAR (HLA-B*58:01 carrier)                                                                                                                                     allopurinol: avoid - allopurinol is contraindicated (risk of severe cutaneous adverse reaction)                                                                           SJS/TEN/DRESS with substantial mortality
17  d49e9f88d9c2         G6PD            rasburicase                                                        G6PD Deficient (WHO class II)                                                                                                                                                         rasburicase: contraindicated - do not use; alternatives include allopurinol                                                   Contraindicated; severe acute haemolysis and methaemoglobinaemia
18  3786ab9a929d         G6PD            rasburicase                                                       G6PD Deficient (WHO class III)                                                                                                                                                         rasburicase: contraindicated - do not use; alternatives include allopurinol                                                   Contraindicated; severe acute haemolysis and methaemoglobinaemia
19  2a8544a44d5f         G6PD             primaquine                                                       G6PD Deficient (WHO class III)          primaquine: avoid standard 14-day dosing - high risk of acute haemolytic anaemia; if radical cure is needed use the WHO/CDC weekly regimen (0.75 mg/kg or 45 mg once weekly x8 weeks) with close monitoring for haemolysis                                      Acute haemolytic anaemia; can be severe and life-threatening at 14-day dosing
20  369c2bcff713      MT-RNR1        aminoglycosides                        MT-RNR1 increased risk of aminoglycoside-induced hearing loss                                                                         aminoglycosides: avoid unless the high risk of permanent hearing loss is outweighed by the severity of infection and a lack of safe, effective alternatives           Not fatal, but permanent bilateral hearing loss after a single standard course (irreversible major harm)
21  1229a4123378         RYR1  volatile-anaesthetics                                                   Malignant Hyperthermia susceptible                                                              volatile anaesthetics (and succinylcholine): relatively contraindicated - do not use except in extraordinary circumstances; use a non-triggering anaesthetic technique                                                    Malignant hyperthermia crisis; rapidly fatal without dantrolene